spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:h2db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false
    open-in-view: false
    hibernate:
     ddl-auto: update
  thymeleaf:
    content-type: text/html
    cache: false
    mode: LEGACYHTML5